- name: Install and start Ubuntu services
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Ubuntu packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql-server
        - php
        - php-mysql  # Install PHP module for MySQL connectivity
        - redis-server
        - vsftpd  # FTP server package

    - name: Start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mysql
        - vsftpd
        - redis-server
