---
- name: Install and start services playbook
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Ubuntu packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - apache2
        - mysql-server
        - php
        - git

    - name: Start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - apache2
        - mysql