---
- hosts: ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: /tmp/test.test
        dest: ~/
    - name: install nginx # name of the play
      yum:
        name: nginx
        state: latest
        update_cache: yes
    - name: start and enable autostart of nginx server
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: Status of nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
    - name: Start service nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started
