name: Ansible test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  ansible-test:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose a Python version compatible with Ansible
    
      - name: Clone ansible
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'pauldchang'
          repository: 'ansible'
    
      - name: Access cloned repo
        run: |
          cd ansible
          ls -la

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          # Replace 18.220.23.33 with the hostname of the machine you're SSH-ing into
          ssh-keyscan ec2-18-220-23-33.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          # UBUNTU_SSH_KEY is the name of the repository secret
          echo "${{ secrets.UBUNTU_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          eval $(ssh-agent)
          ssh-add ~/.ssh/github_actions
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
  
      - name: Install dependencies
        run: yarn

      - name: Build and deploy
        run: |
          # Add your build and deploy commands here

      - name: Run Ansible Playbook
        run: |
          # Adjust the playbook path and inventory file as needed
          ansible-playbook -i inventory ubuntu.yaml

